import "./css/style.css";

import { Delius_Unicase, Inter, Plus_Jakarta_Sans } from "next/font/google";

import localFont from "next/font/local";

import Header from "@/components/ui/header";
import Banner from "@/components/banner";
import CallCenter from "@/components/call-center";

const myFont = localFont({
  src: "./font/calsans.ttf",
  variable: "--font-calsans",
});

const bos = localFont({
  src: "./font/bookmanoldstyle.ttf",
  variable: "--font-bos",
});

const cambria = localFont({
  src: "./font/cambria.ttf",
  variable: "--font-cambria",
});

const delius = Delius_Unicase({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-delius",
});

const inter = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "E-Laut Kementerian Kelautan dan Perikanan RI",
  description: "Generated by create next app",
  icons: ["/logo-kkp.png"],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${myFont.variable} ${delius.variable} ${bos.variable} ${cambria.variable} antialiased bg-white text-gray-900 tracking-tight `}
      >
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip relative">
          <Header />
          {children}

        </div>
      </body>
    </html>
  );
}
